### ISSUE TITLE
[BUG]paper init

### ISSUE THREAD

**Issue by berubou** [DhyanaChina/simpler-paper#55]
Type:
- [x] Bug
- [ ] Feature
- [ ] Help   

Version:   
latest

Description:  
![image](https://user-images.githubusercontent.com/14237234/33008686-0483f962-ce0f-11e7-9d91-2912a99259bf.png)

Folder names need to limit or Change the rules for creating folder.
when i use `paper init` and enter the folder name with blank spaces inside, it will create folders with the every input that separated by spaces.
and error with `no such file or directory`, the name with blank spaces inside will not be found.

**Comment by unix** [comment]
thx.
how about ban space?

**Comment by unix** [comment]
fixed, see #56
