### ISSUE TITLE
paper build 报错

### ISSUE THREAD

**Issue by Tony1952466760** [DhyanaChina/simpler-paper#81]
运行
`paper build `
报错
![image](https://user-images.githubusercontent.com/11804148/33641735-c40ef2fa-da71-11e7-8407-9c781439f80b.png)

**Comment by Tony1952466760** [comment]
报错内容
- compile to html(node:8976) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: EEXIST: file already exists, mkdir 'E:\NodeJS\node_global\node_modules\simpler-paper\templates\temp'
(node:8976) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
\ compile to html

**Comment by berubou** [comment]
@Tony1952466760 
额。麻烦使用bash。
不要使用cmd或者power shell。我们没有考虑支持，不好意思。
删除路径‘E:\NodeJS\node_global\node_modules\simpler-paper\templates\temp'指向的temp文件夹再重新运行应该可以解决问题。

**Comment by berubou** [comment]
power shell我会马上测试一下实际运行效果的。

**Comment by berubou** [comment]
测试了下，bash下build能够通过，power shell是不行的。
如果安装了git，可以考虑使用git bash。
或是windows商店里也有bash可以使用。
@Tony1952466760  感谢使用以及反馈。问题处理结果麻烦告知一下

**Comment by berubou** [comment]
@Tony1952466760 记得昨天paper server已经没有问题了。build为什么又出错了呢。。。
