### ISSUE TITLE
移动优化

### ISSUE THREAD

**Issue by ghost** [DhyanaChina/simpler-paper#82]
已经反馈夸克浏览器
先关掉

**Comment by unix** [comment]
@dxxt 有几个细节需要描述一下：
问题出现在夸克 PC 还是 Mobile ，还是都有。
请问你使用的是 windows 还是 mac 。谢谢。

**Comment by dxxt** [comment]
手机浏览器
http://www.myquark.cn

**Comment by berubou** [comment]
@dxxt 
额。。。手机目前没有兼容。
想要查看效果可以qq直接点击链接打开，
手机浏览器想要查看，建议修改浏览器标识为电脑。
